### PR TITLE
Checkbox + Radio: update dimensions

### PR DESCRIPTION
**Pull request by jyash97**
Before: 
Before

After:
After

### CODE REVIEW

**Comment by bpierre** [comment]
Hi @jyash97, could you please indicate your browser version? It looks like an issue with subpixel rendering on Blink, which I thought was solved in recent versions. Thanks!

**Comment by jyash97** [comment]
Hey I found this one: Chrome version - 78.0.3904.70 (Official Build) (64-bit)

**Comment by bpierre** [comment]
Hi @jyash97, I could reproduce it! It seems Chrome doesn’t have subpixel rendering on macOS (except when using 3D transforms) and maybe Windows, while it does on the Linux release (which is the one I use :s).

I also noticed that the checkbox and radio dimensions were incorrect: they have been updated in the design system but weren’t up to date in aragonUI. I added a commit to the PR to do this.

Let me know if you notice any other issue!

**Comment by jyash97** [comment]
Hey @bpierre thanks for the update. I am glad that the issue has been fixed :)

If possible you can check #636

**Pull request merged**
