### PR TITLE
Export all the utils

### PR DESCRIPTION
**Pull request by bpierre**
New exports:

- ~`cachedMap()`~
- `prefixUrl()`
- `ensureTrailingSlash()`
- `map()`, `norm()`, `lerp()`, `clamp()`
- `random()`, `randomInt()`

Closes https://github.com/aragon/aragon-ui/issues/193

### CODE REVIEW

**Comment by sohkai** [comment]
Just not sure about `cachedMap()`—do you think that'll be really useful to others?

**Comment by bpierre** [comment]
> Just not sure about cachedMap()—do you think that'll be really useful to others?

I’m not sure it would be useful, but the intention is to export all of `utils/` without exception. Maybe we could create a `lib/` directory for the things we don’t want to expose, and put `cachedMap()` in there?

**Comment by sohkai** [comment]
> Maybe we could create a lib/ directory for the things we don’t want to expose, and put cachedMap() in there?

Yep, that sounds good!

**Comment by bpierre** [comment]
@sohkai Done!

**Pull request merged**
