### PR TITLE
re-align RadioListItem button to top of component

### PR DESCRIPTION
**Pull request by stvtortora**
Fixes aragon/aragon#1340

### CODE REVIEW

**Comment by stvtortora** [comment]
Hi, any update on this one?

**Comment by bpierre** [comment]
Hi @stvtortora, sorry for the delay, I am checking now.

I noticed the spacing wasn’t exactly the same as the Figma file (1px vs. 4px). The default on `Radio` is 4px already, so I think we could remove the line altogether?

**Comment by stvtortora** [comment]
Hi @bpierre. No worries. I removed that line, but I don't think its what we want because no default value took its place. As far as I can tell, there does not appears to be a file (or any code for that matter) with "Figma" in this repository.

**Comment by bpierre** [comment]
> As far as I can tell, there does not appears to be a file (or any code for that matter) with "Figma" in this repository.

Ah sorry I should have been more explicit, I was referring to the link to Figma in the issue: https://www.figma.com/file/bZ1j7omfhdMCbtFahP3nEJ9B/Client?node-id=525%3A1141

I was just testing and it seems correct now?

**Comment by stvtortora** [comment]
@bpierre Ah, ok, thanks for clarifying! It looks good to me too.

**Pull request merged**
