### PR TITLE
Add DateRangePicker (prev. experimental DateRange)

### PR DESCRIPTION
**Pull request by adekbadek**
Fixes https://github.com/aragon/aragon-ui/issues/513

This implements a new design and functionality for `DateRangePicker` component:

- UX: ranges can now be selected more easily, both in one of the calendars as well as across both calendars
- refactoring: code was cleaned up and components changed to functional (instead of class-based)
- rename `DateRange` to `DateRangePicker` and move it to regular exports (not experimental `_DateRange` anymore)

Before selection:

image

Range selected:

image

### CODE REVIEW

**Comment by lcoenen** [comment]
This conflict with my PR :( #623 I implemented the same features (range). I guess I will let mine be stale.

**Comment by bpierre** [comment]
Hi @lcoenen, I contacted you on Aragon Chat yesterday about this, and the TextCopy PR. Unfortunately we had started this version internally and I didn’t know you were working on it as well :disappointed:

We are going to have a look at your PR and see if there are things that we could reuse for the new version. I hope you didn’t spend too much time on it… I am really sorry this happened. Let me know if you plan to work on something else so we can sync before you start! (`bpierre` on Aragon Chat) :smiley:

**Comment by lcoenen** [comment]
I did not recieve this message. The main feature I add is the partial property, so maybe we can rebase that. I add an "infinite" marker with a fadding, we can use if this looks good to you :)

**Comment by adekbadek** [comment]
added improvements:

1. [x] focused state & keyboard interaction
1. [x] dates on calendar - make focusable. With that and the point above, it's now possible to complete the whole interaction with keyboard only 🚀
1. [x] styling - pressed state when closed
1. [x] "pick a range then close without applying, then reopen" bug - fixed so now on closing the date picker, local state is reset
1. [x] styling - spacing between rows fix
1. [x] using `Popover` for better placement and open/close animation
1. [x] remove named export
1. [x] add gallery page. There's an issue with that though, because `Viewport`handles gallery page's window, not the iframe in which the demo is presented :/

**Comment by bpierre** [comment]
@adekbadek Merged, thank you :heart: :heart: :heart:

**Pull request merged**
